name: Next.js CI/CD - Deploy to HomeServer

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: '20' # ← node 20으로 변경!

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Prepare deployment package
        run: |
          mkdir -p deploy  
          cp -r .next deploy/  
          cp -r public deploy/  
          cp package.json package-lock.json deploy/  
          cp -r node_modules deploy/

      - name: Upload to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          source: 'deploy/*'
          target: '/home/junji/feed-news' # ← 변경

      - name: Restart Server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /home/junji/feed-news  
            npm ci --omit=dev  
            pm2 reload feed-news || pm2 start npm --name "feed-news" -- start    # ← 변경
